In [5]:
%%html
<link href="https://aegis4048.github.io/theme/libs/prism.css" rel="stylesheet" />
<link href="https://aegis4048.github.io/jupyter_custom.css" rel="stylesheet" />
<script src="https://aegis4048.github.io/theme/libs/prism.js"></script>
<script src="https://aegis4048.github.io/jupyter_custom.js"></script>

If you’ve ever tried to do anything with data provided to you in PDFs, you know how painful it is — it's hard to copy-and-paste rows of data out of PDF files. It's especially hard if you want to retain the formats of the data in PDF file while extracting text. Most of the open source PDF parsers available are good at extracting text. But when it comes to retaining the the file's structure, eh, not really. Try [tabula-py](https://github.com/chezou/tabula-py) to extract data into a CSV or Microsoft Excel spreadsheet using a simple, easy-to-use interface. One look is worth a thousand words. Take a look at the demo screenshot.
 
<div class="row">
    <div class="col"><img src="jupyter_images/pdf_parse_demo.png"></div>
</div>

## Installations

This installation tutorial assumes that you are using Windows operating system. However, according to the offical [tabula-py documentation](https://github.com/chezou/tabula-py#os), it was confirmed that tabula-py works on macOS and Ubuntu. 


**1. Download Java**

Tabula-py is a wrapper for tabula-java, which translates Python commands to Java commands, so that us Python programmers don't have to bother learning Java. As the name "tabula-java" suggests, it requires Java. You can download Java [here](https://www.java.com/en/).

**2. Set environment PATH variable (Windows)**

One thing that I don't like about Windows is that it's difficult to use a new program I downloaded in a console environment like Python or CMD window. But oh well, if you are a Windows user, you have to go through this extra step to allow Python to use Java. If you are a macOS or Ubuntu user, you probably don't need this step. 

Find where Java is installed, and go to <code>Control Panel > System and Security > System > Advanced system settings > Advanced > Environment Variables...</code> to set environment PATH variable for Java.
<div class="row give-margin">
    <div class="col-6"><img src="jupyter_images/tabula_instruction_1.png" style="border: 1px solid;"></div>
    <div class="col-6"><img src="jupyter_images/tabula_instruction_2.png" style="border: 1px solid;"></div>
</div>

Make sure you have <code>Java\jdk1.8.0_201\bin</code> and <code>Java\jre1.8.0_201\bin</code> in the environment path variable. Then, type <code>java -version</code> on CMD window. If you successfully installed Java and configured the environment variable, you should see something like this:

<pre class="command-line language-powershell" data-prompt="PS C:\Users\Eric>" data-output="2-5">
<code class="language-powershell">java -version
    
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
</code>
</pre>

If you don't see something like this, it means that you didn't properly configure environment PATH variable for Java.

**3. Re-start Your Command Prompt**

Any program invoked from the command prompt will be given the environment variables that was at the time the command prompt was invoked. If you launched your Python console or Jupyter Notebook before you updated your environment PATH variable, you need to re-start again. Otherwise the change in the environment variable will not be reflected.

If you are experiencing <code>FileNotFoundError</code> or <code>'java' is not recognized as an internal or external command, operable program or batch file</code> inside Jupyter or Python console, it's the issue of environment variable. Either you set it wrong, or your command prompt is not reflecting the change you made in the environment variable.

To check if the change in the environment variable was reflected, run the following code in Jupyter or Python console:
<pre>
    <code class="language-python">
        import os
        
        s = os.environ["PATH"].split(';')
        for item in s: 
            print(item)
    </code>
</pre>

Something like these must be in the output if everything is working fine:

<pre>
    <code class="language-markup">
        C:\Program Files\Java\jdk1.8.0_201\bin
        C:\Program Files\Java\jre1.8.0_201\bin
    </code>
</pre>

**4. Install Tabula-py**

This is the last step:
<pre class="command-line language-powershell" data-prompt="C:\Users\Eric>">
<code class="language-powershell">pip install tabula-py
</code>
</pre>

More detailed instructions are provided in the [github repo](https://github.com/chezou/tabula-py) of tabula-py

## Tabula Web Application

Tabula supports web application to parse PDF files. You do not need this to use tabula-py, but from my personal experience I strongly recommend you to use this tool because it really helps you debugging issues when using tabula-py. For example, I was tring to parse 100s of PDF files at once, and for some reason tabula-py would return an <code>NoneType</code> object instead of <code>pd.DataFrame</code> object (by default, tabula-py extracts tables in dataframe) for one PDF file. There was nothing wrong with my codes, and yet it would just not parse the file. So I tried opening it on the tabula web-app, and realized that it was actually a scanned PDF file and that tabula is unable to parse scanned PDFs. 

Long stort shot, if it can be parsed with tabula web-app, you can replicate it with tabula-py. If tabula web-app can't, you should look for a different tool to meet your need.

**Installations**

If you already configured the environment PATH variable for Java, all you need to do is downloading the .zip file [here](https://tabula.technology/) and running <code>tabula.exe</code>. That's it. Tabula has really nice web-interface in which you can parse tables from PDFs by just clicking buttons.

<div class="alert alert-info">
    <h4>Note</h4>
    <p>The web-app will automatically open in your browser with <strong>127.0.0.1:8080</strong> local host. If port 8080 is already being used by another process, you will need to shut it down. But normally you don't have to worry about this.</p>
</div>

**Screenshots**

This is what you will see when you launch <code>tabula.exe</code>. <code>Browse</code> the PDF file you want to parse, and <code>import</code>.

<div class="row give-margin">
    <div class="col"><img src="jupyter_images/tabula-webapp.png"></div>
</div>

You can either use <code>Autodetect Tables</code> or drag your mouse to choose the area of your interest. If the PDF file has a  complicated structure, it is usually better to manually choose the area of your interest. Also, note the option <code>Repeat to All Pages</code>. Selecting this option will apply the area you chose for all pages.

<div class="row give-margin">
    <div class="col"><img src="jupyter_images/tabula-webapp_2.png"></div>
</div>

Here's the output. More explanation about <code>Lattice</code> and <code>Stream</code> options will be discussed in detail later.

<div class="row give-margin">
    <div class="col"><img src="jupyter_images/tabula-webapp_3.png"></div>
</div>

## Running Tabula-py

Tabula-py enables you to extract table from PDF into DataFrame and JSON. It also can extract tables from PDF and save file as CSV, TSV or JSON. Some basic code examples are as follows:

<pre>
    <code class="language-python">
        import tabula

        # Read pdf into DataFrame
        df = tabula.read_pdf("test.pdf", options)

        # Read remote pdf into DataFrame
        df2 = tabula.read_pdf("https://github.com/tabulapdf/tabula-java/raw/master/src/test/resources/technology/tabula/arabic.pdf")

        # convert PDF into CSV
        tabula.convert_into("test.pdf", "output.csv", output_format="csv")

        # convert all PDFs in a directory
        tabula.convert_into_by_batch("input_directory", output_format='csv')
    </code>
</pre>

**Area Selection**

You decide a portion of PDF you want to analyze by setting <code>area</code> (top,left,bottom,right) option in <code>tabula.read_pdf()</code>. This is equivalent to dragging your mouse and setting the area of your interest in tabula web-app as it was mentioned above. Also note that you can choose the page, or pages you want to parse with <code>pages</code> option.

According to the offical documentation:

<pre>
    <code class="language-markup">
        pages (str, int, list of int, optional)

            An optional values specifying pages to extract from. It allows str, int, list of int.
            Example: 1, '1-2,3', 'all' or [1,2]. Default is 1
    </code>
</pre>    
    
The sample PDF file can be downloaded from [here](https://github.com/aegis4048/aegis4048.github.io-source/blob/master/content/downloads/notebooks/pdf_parsing/lattice-timelog-multiple-pages.pdf).

In [30]:
file = 'pdf_parsing/lattice-timelog-multiple-pages.pdf'
df = tabula.read_pdf(file, lattice=True, pages=2, area=(406, 24, 695, 589))

In [31]:
df

,Start Date,End Date,(hr),Activity,Activity Detail,Operation,Com
0,12/13/2014\r06:00,12/13/2014\r09:00,3.0,SURF-DRILL,DRILL SURFACE,DRL,Rotate from 1600' to 1859' (259' @ 8 fph). WOB...
1,12/13/2014\r09:00,12/13/2014\r11:00,2.0,SURF-CIRC,CIRCULATE,CIRC,Pump 2- 50 bbl hi vis sweep; Circulate to surface
2,12/13/2014\r11:00,12/13/2014\r14:00,3.0,SURF-TRIP,TOOH,TRIP,TOOH (Slick off bottom) f/1859' to 108' (SLM)...
3,12/13/2014\r14:00,12/13/2014\r16:00,2.0,PLAN,EQUIP,BHA,"PJSA - Break bit & L/D directional BHA, clean ..."
4,12/13/2014\r16:00,12/13/2014\r17:30,1.5,PLAN,DRLG,CSG,PTJSA / R/U Pipe Pros.Csg. tools / PTJSA on ru...
5,12/13/2014\r17:30,12/13/2014\r18:00,0.5,PLAN,DRLG,CSG,Make up 13 3/8 Gemco PDC drillable float shoe;...
6,12/13/2014\r18:00,12/13/2014\r18:30,0.5,PLAN,PERS,SFTY,"HJSM with Morning tour crew, Pipe Pro casing c..."
7,12/13/2014\r18:30,12/13/2014\r23:30,5.0,PLAN,DRLG,CSG,"Make up 13 /8"" PDC drillable float collar onto..."
8,12/13/2014\r23:30,12/14/2014\r01:30,2.0,SURF-CIRC,CIRCULATE,CIRC,HJSM on Hoisting personal; Make up Swedge in ...
9,12/14/2014\r01:30,12/14/2014\r03:30,2.0,PLAN,DRLG,CSG,"Run 13 3/8""J-55 54.5 BTC f/ 1,639' to 1,819';..."
10,12/14/2014\r03:30,12/14/2014\r04:30,1.0,SURF-CIRC,CIRCULATE,CIRC,Circulate Bttms up while Rigging down csg crew...
11,12/14/2014\r04:30,12/14/2014\r06:00,1.5,SURF-CMT,CEMENT SURFACE\rCASING,CMT,"HJSM w/ Basic Cementer, H&P rig crew & PNR; D..."

Alternatively, you can set area with percentage scale by setting <code>relative_area=True</code>. For this specific PDF file, the below <code>area=(50, 5, 92, 100), relative_area=True</code> option is equivalent to <code>area=(406, 24, 695, 589)</code> above.

In [35]:
file = 'pdf_parsing/lattice-timelog-multiple-pages.pdf'
df = tabula.read_pdf(file, lattice=True, pages=2, area=(50, 5, 92, 100), relative_area=True)

In [36]:
df

,Start Date,End Date,Dur (hr),Activity,Activity Detail,Operation,Com
0,2/13/2014\r6:00,12/13/2014\r09:00,3.0,SURF-DRILL,DRILL SURFACE,DRL,Rotate from 1600' to 1859' (259' @ 8 fph). WOB...
1,2/13/2014\r9:00,12/13/2014\r11:00,2.0,SURF-CIRC,CIRCULATE,CIRC,Pump 2- 50 bbl hi vis sweep; Circulate to surface
2,2/13/2014\r1:00,12/13/2014\r14:00,3.0,SURF-TRIP,TOOH,TRIP,TOOH (Slick off bottom) f/1859' to 108' (SLM)...
3,2/13/2014\r4:00,12/13/2014\r16:00,2.0,PLAN,EQUIP,BHA,"PJSA - Break bit & L/D directional BHA, clean ..."
4,2/13/2014\r6:00,12/13/2014\r17:30,1.5,PLAN,DRLG,CSG,PTJSA / R/U Pipe Pros.Csg. tools / PTJSA on ru...
5,2/13/2014\r7:30,12/13/2014\r18:00,0.5,PLAN,DRLG,CSG,Make up 13 3/8 Gemco PDC drillable float shoe;...
6,2/13/2014\r8:00,12/13/2014\r18:30,0.5,PLAN,PERS,SFTY,"HJSM with Morning tour crew, Pipe Pro casing c..."
7,2/13/2014\r8:30,12/13/2014\r23:30,5.0,PLAN,DRLG,CSG,"Make up 13 /8"" PDC drillable float collar onto..."
8,2/13/2014\r3:30,12/14/2014\r01:30,2.0,SURF-CIRC,CIRCULATE,CIRC,HJSM on Hoisting personal; Make up Swedge in ...
9,2/14/2014\r1:30,12/14/2014\r03:30,2.0,PLAN,DRLG,CSG,"Run 13 3/8""J-55 54.5 BTC f/ 1,639' to 1,819';..."
10,2/14/2014\r3:30,12/14/2014\r04:30,1.0,SURF-CIRC,CIRCULATE,CIRC,Circulate Bttms up while Rigging down csg crew...
11,2/14/2014\r4:30,12/14/2014\r06:00,1.5,SURF-CMT,CEMENT SURFACE\rCASING,CMT,"HJSM w/ Basic Cementer, H&P rig crew & PNR; D..."


Default is the entire page. 


**Lattice Mode vs Stream Mode**

Tabula supports two primary modes of table extraction — Lattice mode and stream mode. 

<p><u>Lattice Mode</u></p>

Lattice mode forces PDF to be extracted using lattice-mode extraction. It recognizes each cells based on ruling lines, or borders of each cell. 

<p><u>Stream Mode</u></p>

Stream mode forces PDF to be extracted using stream-mode extraction. This mode is used when there are no ruling lines to differentiate one cell from the other. Instead, it uses spacings among each cells to recognize each cell.

<div class="row give-margin">
    <div class="col-md-6 col-sm-12">
        <div class="col-12"><img src="jupyter_images/lattice_mode.png" style="border: 1px solid; height: 380px"></div>
        <div class="col-12"><p class="image-description">Lattice mode recommended</p></div>
    </div>
    <div class="col-md-6 col-sm-12">
        <div class="col-12"><img src="jupyter_images/stream_mode_2.png" style="border: 1px solid; height: 380px"></div>
        <div class="col-12"><p class="image-description">Stream mode recommended</p></div>
    </div>
</div>

**Lattice

In [6]:
import tabula
import pandas as pd

In [17]:
file = 'pdf_parsing/lattice-survey-single-page.pdf'
df = tabula.read_pdf(file, lattice=True,area=(25, 0, 90, 100), relative_area=True)
df

,Int #,#,Date,Type,Top (ftKB),Top (TVD) (ftKB),Btm (ftKB),Btm (TVD) (ftKB),Job
0,68,5,2/9/2016 16:19,CONVENTIONAL PERF,"9,071.0","8,913.9","9,073.0","8,914.6","OCM, 1/16/2015 00:00"
1,68,4,2/9/2016 16:18,CONVENTIONAL PERF,"9,101.0","8,923.8","9,103.0","8,924.4","OCM, 1/16/2015 00:00"
2,68,3,2/9/2016 16:17,CONVENTIONAL PERF,"9,131.0","8,931.4","9,133.0","8,931.8","OCM, 1/16/2015 00:00"
3,68,2,2/9/2016 16:16,CONVENTIONAL PERF,"9,161.0","8,936.9","9,163.0","8,937.2","OCM, 1/16/2015 00:00"
4,68,1,2/9/2016 16:15,CONVENTIONAL PERF,"9,191.0","8,940.9","9,193.0","8,941.2","OCM, 1/16/2015 00:00"
5,67,5,2/9/2016 13:31,CONVENTIONAL PERF,"9,221.0","8,944.2","9,223.0","8,944.4","OCM, 1/16/2015 00:00"
6,67,4,2/9/2016 13:30,CONVENTIONAL PERF,"9,251.0","8,947.0","9,253.0","8,947.2","OCM, 1/16/2015 00:00"
7,67,3,2/9/2016 13:29,CONVENTIONAL PERF,"9,281.0","8,949.6","9,283.0","8,949.7","OCM, 1/16/2015 00:00"
8,67,2,2/9/2016 13:28,CONVENTIONAL PERF,"9,311.0","8,952.0","9,313.0","8,952.1","OCM, 1/16/2015 00:00"
9,67,1,2/9/2016 13:27,CONVENTIONAL PERF,"9,341.0","8,954.2","9,343.0","8,954.3","OCM, 1/16/2015 00:00"
10,66,5,2/9/2016 10:59,CONVENTIONAL PERF,"9,371.0","8,956.3","9,373.0","8,956.4","OCM, 1/16/2015 00:00"
11,66,4,2/9/2016 10:58,CONVENTIONAL PERF,"9,401.0","8,958.3","9,403.0","8,958.4","OCM, 1/16/2015 00:00"
12,66,3,2/9/2016 10:57,CONVENTIONAL PERF,"9,431.0","8,960.2","9,433.0","8,960.3","OCM, 1/16/2015 00:00"
13,66,2,2/9/2016 10:56,CONVENTIONAL PERF,"9,461.0","8,961.9","9,463.0","8,962.0","OCM, 1/16/2015 00:00"
14,66,1,2/9/2016 10:55,CONVENTIONAL PERF,"9,491.0","8,963.5","9,493.0","8,963.6","OCM, 1/16/2015 00:00"
15,65,5,2/9/2016 07:57,CONVENTIONAL PERF,"9,521.0","8,965.0","9,523.0","8,965.0","OCM, 1/16/2015 00:00"
16,65,4,2/9/2016 07:56,CONVENTIONAL PERF,"9,551.0","8,966.2","9,553.0","8,966.3","OCM, 1/16/2015 00:00"
17,65,3,2/9/2016 07:55,CONVENTIONAL PERF,"9,581.0","8,967.4","9,583.0","8,967.4","OCM, 1/16/2015 00:00"
18,65,2,2/9/2016 07:54,CONVENTIONAL PERF,"9,611.0","8,968.3","9,613.0","8,968.4","OCM, 1/16/2015 00:00"
19,65,1,2/9/2016 07:53,CONVENTIONAL PERF,"9,641.0","8,969.1","9,643.0","8,969.1","OCM, 1/16/2015 00:00"
20,64,5,2/9/2016 03:35,CONVENTIONAL PERF,"9,671.0","8,969.6","9,673.0","8,969.7","OCM, 1/16/2015 00:00"
21,64,4,2/9/2016 03:34,CONVENTIONAL PERF,"9,701.0","8,970.0","9,703.0","8,970.0","OCM, 1/16/2015 00:00"
22,64,3,2/9/2016 03:33,CONVENTIONAL PERF,"9,731.0","8,970.2","9,733.0","8,970.2","OCM, 1/16/2015 00:00"
23,64,2,2/9/2016 03:32,CONVENTIONAL PERF,"9,761.0","8,970.4","9,763.0","8,970.4","OCM, 1/16/2015 00:00"
24,64,1,2/9/2016 03:31,CONVENTIONAL PERF,"9,791.0","8,970.5","9,793.0","8,970.6","OCM, 1/16/2015 00:00"
25,63,5,2/9/2016 00:38,CONVENTIONAL PERF,"9,821.0","8,970.8","9,823.0","8,970.8","OCM, 1/16/2015 00:00"
26,63,4,2/9/2016 00:37,CONVENTIONAL PERF,"9,851.0","8,971.3","9,853.0","8,971.3","OCM, 1/16/2015 00:00"
27,63,3,2/9/2016 00:36,CONVENTIONAL PERF,"9,881.0","8,972.1","9,883.0","8,972.1","OCM, 1/16/2015 00:00"
28,63,2,2/9/2016 00:35,CONVENTIONAL PERF,"9,911.0","8,973.0","9,913.0","8,973.0","OCM, 1/16/2015 00:00"
29,63,1,2/9/2016 00:34,CONVENTIONAL PERF,"9,941.0","8,973.5","9,943.0","8,973.5","OCM, 1/16/2015 00:00"
30,62,5,2/8/2016 21:39,CONVENTIONAL PERF,"9,971.0","8,973.8","9,973.0","8,973.9","OCM, 1/16/2015 00:00"
31,62,4,2/8/2016 21:38,CONVENTIONAL PERF,"10,001.0","8,974.9","10,003.0","8,975.0","OCM, 1/16/2015 00:00"
32,62,3,2/8/2016 21:37,CONVENTIONAL PERF,"10,031.0","8,976.0","10,033.0","8,976.0","OCM, 1/16/2015 00:00"
33,62,2,2/8/2016 21:36,CONVENTIONAL PERF,"10,061.0","8,976.8","10,063.0","8,976.9","OCM, 1/16/2015 00:00"
34,62,1,2/8/2016 21:35,CONVENTIONAL PERF,"10,091.0","8,977.5","10,093.0","8,977.6","OCM, 1/16/2015 00:00"
35,61,5,2/8/2016 18:52,CONVENTIONAL PERF,"10,121.0","8,978.3","10,123.0","8,978.3","OCM, 1/16/2015 00:00"
36,61,4,2/8/2016 18:51,CONVENTIONAL PERF,"10,151.0","8,979.1","10,153.0","8,979.2","OCM, 1/16/2015 00:00"
37,61,3,2/8/2016 18:50,CONVENTIONAL PERF,"10,181.0","8,980.1","10,183.0","8,980.1","OCM, 1/16/2015 00:00"
38,61,2,2/8/2016 18:49,CONVENTIONAL PERF,"10,211.0","8,980.9","10,213.0","8,980.9","OCM, 1/16/2015 00:00"
39,61,1,2/8/2016 18:48,CONVENTIONAL PERF,"10,241.0","8,981.4","10,243.0","8,981.5","OCM, 1/16/2015 00:00"
40,60,5,2/8/2016 15:47,CONVENTIONAL PERF,"10,271.0","8,981.8","10,273.0","8,981.8","OCM, 1/16/2015 00:00"
41,60,4,2/8/2016 15:46,CONVENTIONAL PERF,"10,301.0","8,981.9","10,303.0","8,981.9","OCM, 1/16/2015 00:00"
42,60,3,2/8/2016 15:45,CONVENTIONAL PERF,"10,331.0","8,981.7","10,333.0","8,981.7","OCM, 1/16/2015 00:00"
43,60,2,2/8/2016 15:44,CONVENTIONAL PERF,"10,361.0","8,981.3","10,363.0","8,981.2","OCM, 1/16/2015 00:00"
44,60,1,2/8/2016 15:43,CONVENTIONAL PERF,"10,391.0","8,980.7","10,393.0","8,980.6","OCM, 1/16/2015 00:00"
45,59,5,2/8/2016 13:03,CONVENTIONAL PERF,"10,421.0","8,980.1","10,423.0","8,980.0","OCM, 1/16/2015 00:00"
46,59,4,2/8/2016 13:02,CONVENTIONAL PERF,"10,451.0","8,979.5","10,453.0","8,979.4","OCM, 1/16/2015 00:00"
47,59,3,2/8/2016 13:01,CONVENTIONAL PERF,"10,481.0","8,978.9","10,483.0","8,978.8","OCM, 1/16/2015 00:00"
48,59,2,2/8/2016 13:00,CONVENTIONAL PERF,"10,511.0","8,978.2","10,513.0","8,978.2","OCM, 1/16/2015 00:00"
49,59,1,2/8/2016 00:00,CONVENTIONAL PERF,"10,541.0","8,977.6","10,543.0","8,977.6","OCM, 1/16/2015 00:00"
50,58,5,2/8/2016 09:59,CONVENTIONAL PERF,"10,571.0","8,977.0","10,573.0","8,977.0","OCM, 1/16/2015 00:00"
51,58,4,2/8/2016 09:58,CONVENTIONAL PERF,"10,601.0","8,976.3","10,603.0","8,976.2","OCM, 1/16/2015 00:00"
52,58,3,2/8/2016 09:57,CONVENTIONAL PERF,"10,631.0","8,975.5","10,633.0","8,975.5","OCM, 1/16/2015 00:00"
53,58,2,2/8/2016 09:56,CONVENTIONAL PERF,"10,661.0","8,974.6","10,663.0","8,974.6","OCM, 1/16/2015 00:00"
54,58,1,2/8/2016 09:55,CONVENTIONAL PERF,"10,691.0","8,973.7","10,693.0","8,973.6","OCM, 1/16/2015 00:00"
55,57,5,2/8/2016 05:03,CONVENTIONAL PERF,"10,721.0","8,972.7","10,723.0","8,972.6","OCM, 1/16/2015 00:00"
56,57,4,2/8/2016 05:02,CONVENTIONAL PERF,"10,751.0","8,971.6","10,753.0","8,971.6","OCM, 1/16/2015 00:00"
57,57,3,2/8/2016 05:01,CONVENTIONAL PERF,"10,781.0","8,970.9","10,783.0","8,970.8","OCM, 1/16/2015 00:00"
58,57,2,2/8/2016 05:00,CONVENTIONAL PERF,"10,811.0","8,970.5","10,813.0","8,970.5","OCM, 1/16/2015 00:00"

In [3]:
df2 = tabula.read_pdf("https://github.com/tabulapdf/tabula-java/raw/master/src/test/resources/technology/tabula/arabic.pdf")

In [4]:
df2

                         مرحباً                 اسمي سلطان
0  انا من ولاية كارولينا الشمال                من اين انت؟
1                          1234                عندي 47 قطط
2                  هل انت شباك؟  اسمي Jeremy في الانجليزية
3      Jeremy is جرمي in Arabic                        NaN

In [ ]:

First, you need sample PDF files. You can choose to use your own PDF files, or download the sample PDF files from my [Github repo](https://github.com/aegis4048/aegis4048.github.io-source/tree/master/content/downloads/notebooks/pdf_parsing).

<div class="alert alert-info">
    <h4>Notes on Sample Data</h4>
    <p>The sample PDF files used in this tutorial are publicly available data from <a href="http://www.utlands.utsystem.edu/API/4200346352">University Land</a>.</p>
</div>